apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: app-3tiers-pipeline
spec:
  workspaces:
    - name: shared-workspace # L'blasa win bech yet7at l'code
  params:
    - name: git-url
      type: string
      description: L'URL mta3 l'projet Git
  tasks:
    # Etape 1: Njibou l'code min Git
    - name: fetch-repository
      taskRef:
        name: git-clone
        kind: Task
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: "main" # Baddalha ken l'branche mta3ek esmha master
    - name: build-backend
      # Etape 2: N'buildiw l'Backend

      taskRef:
        name: buildah
        kind: Task
      runAfter:
        - fetch-repository # Testanna l'Git ykamel
      workspaces:
        - name: source
          workspace: shared-workspace
      params:
        - name: IMAGE
          value: quay.io/riadlinsoft/$(context.pipelineRun.namespace)/backend:$(context.pipelineRun.name) #image-registry.openshift-image-registry.svc:5000/$(context.pipelineRun.namespace)/backend:$(context.pipelineRun.name)
        - name: CONTEXT
          value: backend
        - name: DOCKERFILE
          value: backend/Dockerfile
    - name: build-frontend
      # Etape 3: N'buildiw l'Frontend (fi nafs l'wa9t m3a l'backend)

      taskRef:
        name: buildah
        kind: Task
      runAfter:
        - fetch-repository
      workspaces:
        - name: source
          workspace: shared-workspace
      params:
        - name: IMAGE
          value: quay.io/riadlinsoft/$(context.pipelineRun.namespace)/frontend:$(context.pipelineRun.name) #image-registry.openshift-image-registry.svc:5000/$(context.pipelineRun.namespace)/frontend:$(context.pipelineRun.name)
        - name: CONTEXT
          value: frontend-ui
        - name: DOCKERFILE
          value: frontend-ui/Dockerfile

    - name: update-helm-repo
      taskRef:
        name: update-helm-chart
        kind: Task
      runAfter:
        - build-backend
        - build-frontend
      workspaces:
        - name: source
          workspace: shared-workspace
      params:
        - name: new-tag
          value: $(context.pipelineRun.name)
