apiVersion: v1
kind: Secret
metadata:
  name: git-credentials
  annotations:
     tekton.dev/git-0: https://github.com # Baddalha kenek tekdem b' GitLab
type: kubernetes.io/basic-auth
stringData:
  username: "*****"
  password: "*****"
